=== trushank/XML/XML Assignment 3/src/note.dtd
<!ELEMENT list             (books*)>
<!ELEMENT books				(book*)>          
<!ELEMENT book               (text,author,title,publisher,isbn,year)>
<!ATTLIST books text      	CDATA #IMPLIED>
<!ELEMENT text              (#PCDATA)>
<!ELEMENT author              (#PCDATA)>
<!ELEMENT title              (#PCDATA)>
<!ELEMENT publisher              (#PCDATA)>
<!ELEMENT isbn              (#PCDATA)>
<!ELEMENT year              (#PCDATA)>

=== trushank/XML/XML Assignment 3/bin/books_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "note.dtd">
<list>
<books text="A">
<book>
<text>Abelson, Harold</text>
<title>Struktur und Interpretation von Computerprogrammen. Eine Informatik-Einführung</title>
<author>Harold Abelson</author>
<publisher>Springer Verlag</publisher>
<isbn>3540520430</isbn>
<year>1991</year>
</book>
<book>
<text>Abrahams, Paul W.</text>
<title>Tex for the Impatient</title>
<author>Paul W. Abrahams</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201513757</isbn>
<year>2000</year>
</book>
<book>
<text>Abrams, Brad</text>
<title>.NET Framework Standard Library Annotated Reference, Volume 1: Base Class Library and Extended Numerics Library, 1/e</title>
<author>Brad Abrams</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0321154894</isbn>
<year>2004</year>
</book>
<book>
<text>Adams, Joel</text>
<title>Java: An Introduction to Computing</title>
<author>Joel Adams</author>
<publisher>Prentice Hall</publisher>
<isbn>0130142514</isbn>
<year>2000</year>
</book>
<book>
<text>Adamson, Chris</text>
<title>Quicktime for Java</title>
<author>Chris Adamson</author>
<publisher>O'Reilly &amp; Associates</publisher>
<isbn>0596008228</isbn>
<year>2005</year>
</book>
<book>
<text>Adobe Systems</text>
<title>PostScript(R) Language Reference Manual (2nd Edition)</title>
<author>Adobe Systems</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201181274</isbn>
<year>1990</year>
</book>
<book>
<text>Aho, Al</text>
<title>Compilers -- Principles, Techniques, and Tools (2nd ed)</title>
<author>Al Aho et al.</author>
<publisher>Addison-Wesley</publisher>
<isbn>0321486811</isbn>
<year>2007</year>
</book>
<book>
<text>Aho, Alfred V.</text>
<title>Foundations of Computer Science</title>
<author>Alfred V. Aho</author>
<publisher>W.H. Freeman &amp; Company</publisher>
<isbn>0716782332</isbn>
<year>1992</year>
</book>
<book>
<text>Aho, Alfred V.</text>
<title>The AWK Programming Language</title>
<author>Alfred V. Aho</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>020107981X</isbn>
<year>1988</year>
</book>
<book>
<text>Albahari, Ben</text>
<title>C# Essentials (2nd Edition)</title>
<author>Ben Albahari</author>
<publisher>O'Reilly &amp; Associates</publisher>
<isbn>0596003153</isbn>
<year>2002</year>
</book>
<book>
<text>Andleigh, Prabhat K.</text>
<title>Unix System Architecture</title>
<author>Prabhat K. Andleigh</author>
<publisher>Prentice Hall Trade</publisher>
<isbn>0139498435</isbn>
<year>1989</year>
</book>
<book>
<text>ANSI</text>
<title>Programming Language C</title>
<author>ANSI</author>
<publisher>ANSI</publisher>
<isbn/>
<year>2003</year>
</book>
<book>
<text>Apostol</text>
<title>Selected Papers on Calculus</title>
<author>Apostol et al.</author>
<publisher>MAA</publisher>
<isbn/>
<year>1969</year>
</book>
<book>
<text>Appel, Andrew W.</text>
<title>Modern Compiler Implementation in C: Basic Techniques</title>
<author>Andrew W. Appel</author>
<publisher>Cambridge University Press</publisher>
<isbn>0521586534</isbn>
<year>1997</year>
</book>
<book>
<text>Arnold, Ken</text>
<title>The Java Programming Language</title>
<author>Ken Arnold</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201310066</isbn>
<year>1997</year>
</book>
<book>
<text>AT&amp;T</text>
<title>Programmer's Manual (Unix Programmer's Series Volume 1)</title>
<author>AT&amp;T</author>
<publisher>International Thomson Publishing</publisher>
<isbn>0030475325</isbn>
<year>1990</year>
</book>
</books>
<books text="B">
<book>
<text>Bach, Fred</text>
<title>UNIX Handbuch zur Programmentwicklung</title>
<author>Fred Bach</author>
<publisher>Hanser Fachbuchverlag</publisher>
<isbn>3446151036</isbn>
<year/>
</book>
<book>
<text>Bach, Maurice J.</text>
<title>Design of the UNIX Operating System</title>
<author>Maurice J. Bach</author>
<publisher>Prentice Hall PTR</publisher>
<isbn>0132017997</isbn>
<year>1986</year>
</book>
<book>
<text>Bach, Maurice J.</text>
<title>UNIX</title>
<author>Maurice J. Bach</author>
<publisher>Hanser Fachbuch</publisher>
<isbn>3446156933</isbn>
<year/>
</book>
<book>
<text>Bacon, Jean</text>
<title>Operating Systems</title>
<author>Jean Bacon, Tim Harris</author>
<publisher>Pearson Addison Wesley</publisher>
<isbn>0321117891</isbn>
<year>2003</year>
</book>
<book>
<text>Bagnall, Brian</text>
<title>Core LEGO MINDSTORMS Programming: Unleash the Power of the Java Platform</title>
<author>Brian Bagnall</author>
<publisher>Prentice Hall PTR</publisher>
<isbn>0130093645</isbn>
<year>2002</year>
</book>
<book>
<text>Bal, H.E.</text>
<title>Programming Distributed Systems</title>
<author>H.E. Bal</author>
<publisher>Prentice Hall</publisher>
<isbn>0137220839</isbn>
<year>1991</year>
</book>
<book>
<text>Banahan, Mike</text>
<title>UNIX</title>
<author>Mike Banahan</author>
<publisher>Hanser Fachbuchverlag</publisher>
<isbn>3446139753</isbn>
<year/>
</book>
<book>
<text>Barnes, David</text>
<title>Object-Oriented Programming with Java: An Introduction</title>
<author>David Barnes</author>
<publisher>Prentice Hall</publisher>
<isbn>0130869007</isbn>
<year>2000</year>
</book>
<book>
<text>Barnes, John</text>
<title>Programming in Ada 2005</title>
<author>John Barnes</author>
<publisher>Addison-Wesley</publisher>
<isbn>0321340787</isbn>
<year>2006</year>
</book>
<book>
<text>Baum, Dave</text>
<title>Definitive Guide to LEGO MINDSTORMS, Second Edition</title>
<author>Dave Baum</author>
<publisher>APress</publisher>
<isbn>1590590635</isbn>
<year>2002</year>
</book>
<book>
<text>Baum, Dave</text>
<title>Extreme Mindstorms: an Advanced Guide to Lego Mindstorms</title>
<author>Dave Baum</author>
<publisher>APress</publisher>
<isbn>1893115844</isbn>
<year>2000</year>
</book>
<book>
<text>Bell Labs</text>
<title>Unix Time-Sharing System: Unix Programmer's Manual</title>
<author>Incorporated Bell Telephone Laboratories</author>
<publisher>International Thomson Publishing</publisher>
<isbn>0030617421</isbn>
<year>1983</year>
</book>
<book>
<text>Bell Labs</text>
<title>Unix Time-Sharing System: Unix Programmer's Manual</title>
<author>Inc. Bell Telephone Laboratories</author>
<publisher>International Thomson Publishing</publisher>
<isbn>003061743X</isbn>
<year>1983</year>
</book>
<book>
<text>Bell, C. Gordon</text>
<title>High-Tech Ventures: The Guide for Entrepreneurial Success</title>
<author>C. Gordon Bell</author>
<publisher>Perseus Publishing</publisher>
<isbn>0201563215</isbn>
<year>1991</year>
</book>
<book>
<text>Bennedsen, Jens</text>
<title>Reflections on the Teaching of Programming</title>
<author>Jens Bennedsen, Michael E. Caspersin, Michael Kölling (ed)</author>
<publisher>Springer</publisher>
<isbn>9783540779339</isbn>
<year>2008</year>
</book>
<book>
<text>Bentley, Jon</text>
<title>Programming Pearls (2nd Edition)</title>
<author>Jon Bentley</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201657880</isbn>
<year>1999</year>
</book>
<book>
<text>Bentley, Jon Louis</text>
<title>More Programming Pearls: Confessions of a Coder</title>
<author>Jon Louis Bentley</author>
<publisher>Pearson Education POD</publisher>
<isbn>0201118890</isbn>
<year>1988</year>
</book>
<book>
<text>Bentley, Jon Louis</text>
<title>Writing Efficient Programs</title>
<author>Jon Louis Bentley</author>
<publisher>Prentice Hall Computer Books</publisher>
<isbn>013970244X</isbn>
<year>1982</year>
</book>
<book>
<text>Bercik, Bill</text>
<title>Inside Javascript</title>
<author>Bill Bercik</author>
<publisher>New Riders</publisher>
<isbn>1562055933</isbn>
<year>1996</year>
</book>
<book>
<text>Bergin, Thomas J.</text>
<title>History of Programming Languages, Volume 2</title>
<author>Thomas J. Bergin</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201895021</isbn>
<year>1996</year>
</book>
<book>
<text>Bic, Lubomir</text>
<title>Betriebssysteme</title>
<author>Lubomir Bic, Alan C. Shaw</author>
<publisher>Hanser Fachbuchverlag</publisher>
<isbn>3446155732</isbn>
<year/>
</book>
<book>
<text>Bic, Lubomir</text>
<title>The Logical Design Of Operating Systems</title>
<author>Lubomir Bic, Alan C. Shaw</author>
<publisher>Pearson Higher Education</publisher>
<isbn>0135401968</isbn>
<year>1988</year>
</book>
<book>
<text>Bieberstein, Norbert</text>
<title>Executing SOA</title>
<author>Norbert Bieberstein et al.</author>
<publisher>IBM Press</publisher>
<isbn>0132353741</isbn>
<year>2008</year>
</book>
<book>
<text>Biersdorfer, J.D.</text>
<title>iPod and iTunes: The Missing Manual (3. ed)</title>
<author>J. D. Biersdorfer</author>
<publisher>O’Reilly</publisher>
<isbn>0596008775</isbn>
<year>2005</year>
</book>
<book>
<text>Binstock, Cliff</text>
<title>The XML Schema Complete Reference</title>
<author>Cliff Binstock, Dave Peterson, Mitchell Smith</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0672323745</isbn>
<year>2002</year>
</book>
<book>
<text>Bishop, Judith</text>
<title>C# Concisely</title>
<author>Judith Bishop, Nigel Horspool</author>
<publisher>Pearson Addison Wesley</publisher>
<isbn>0321154185</isbn>
<year>2004</year>
</book>
<book>
<text>Blachman, Nancy</text>
<title>Mathematica Quick Reference, Version 2</title>
<author>Nancy Blachman</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201628805</isbn>
<year>1992</year>
</book>
<book>
<text>Bloch, Arthur</text>
<title>Murphy's Law and Other Reasons Why Things Go Wrong</title>
<author>Arthur Bloch</author>
<publisher>Price Stern Sloan Pub</publisher>
<isbn>0843104287</isbn>
<year>1977</year>
</book>
<book>
<text>Bloch, Joshua</text>
<title>Effective Java Programming Language Guide</title>
<author>Joshua Bloch</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201310058</isbn>
<year>2001</year>
</book>
<book>
<text>Budd, Timothy</text>
<title>A Little Smalltalk</title>
<author>Timothy Budd</author>
<publisher>Addison-Wesley Pub Co</publisher>
<isbn>0201106981</isbn>
<year/>
</book>
<book>
<text>Budd, Timothy A.</text>
<title>C++ For Java Programmers</title>
